name: dast-zap

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install workspaces
        run: npm ci --workspaces

      - name: Start api-backend (PORT 3001)
        env:
          NODE_ENV: production
          PORT: 3001
          JWT_SECRET: dummy
        run: |
          nohup node api-backend/src/server.js > server.log 2>&1 &
          sleep 5
          curl -f http://localhost:3001/health

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:3001'
          fail_action: true
